---
title: "Exploration DIVAT rejection"
author: "alice"
date: "2024-04-16"
output: html_document
---

```{r}
#coltype <- c("guess","text","guess","guess","guess","text")
rejection <- read_excel("C:\\Alice\\1-Universitée\\Stages\\M1-centrale\\DATAS\\ALICE_DATAS\\ALL_VARIABLES_KiTGENIE2024.xlsx", sheet = "rejection",na = "NA",col_types = "text")
```

```{r}
describe(rejection)
```

```{r}
rejection$year_reject <- as.numeric(rejection$year_reject)
hist(rejection$year_reject)
plot(rejection$year_reject,rejection$code_ttt_reject)
```

```{r}
dataframe <- data.frame(row.names = c("missing","part","coments") )
lenght <- length(rejection$id_g)
for (col in names(rejection)) {
  if(sum(is.na(rejection[[col]]))!= 0){
    #cat(col ,":" , sum(is.na(rejection[[col]])),"\n")}
    dataframe[col] <- c(sum(is.na(rejection[[col]])),sum(is.na(rejection[[col]]))/lenght,"random")}
}
```

```{r}
write.xlsx(dataframe, file = "C:\\Alice\\1-Universitée\\Stages\\M1-centrale\\DATAS\\Describe\\explore\\explore_NA.xlsx",sheetName = "rejection", append = TRUE)
```

```{r}
addWorksheet(OUT, "rejection")
writeData(OUT, sheet = "rejection", x = rejection,keepNA = TRUE)
```

```{r}
summary(rejection)
```


