
---
title: "Données fixes DIVAT_clean Nantes"
author: "Alice"
date: "2024-04-16"
output: html_document
---

```{r}
coltype <- c("text","guess","text","guess")
merge_fix <- read_excel("C:\\Alice\\1-Universitée\\Stages\\M1-centrale\\DATAS\\NewDATA\\MERGING_part_3.xlsx", sheet = "recipient_before",na = "NA")

```

```{r}
merge_fix$sexe_ind <- as.factor(merge_fix$sexe_ind)
merge_fix$date_g <- as.Date(merge_fix$date_g)
merge_fix$year_g <- as.numeric(merge_fix$year_g)
merge_fix$type_g <- as.factor(merge_fix$type_g)
merge_fix$rank_g <- as.factor(merge_fix$rank_g)
merge_fix$code_link_rec_don_g <- as.factor(merge_fix$code_link_rec_don_g)
merge_fix$age_predon_r <- as.numeric(merge_fix$age_predon_r)
merge_fix$height_r <- as.numeric(merge_fix$height_r)
merge_fix$weight_r <- as.numeric(merge_fix$weight_r)
merge_fix$bmi_r <- as.numeric(merge_fix$bmi_r)
merge_fix$code_disease <- as.factor(merge_fix$age_predon_r)
merge_fix$delay_abm_g <- as.numeric(merge_fix$delay_abm_g)
merge_fix$delay_dial_g <- as.numeric(merge_fix$delay_dial_g)
merge_fix$code_purif <- as.factor(merge_fix$code_purif)
merge_fix$mach_perf <- as.factor(merge_fix$mach_perf)
merge_fix$nb_dial_post_g <- as.numeric(merge_fix$nb_dial_post_g)
merge_fix$day_resemption_fct_g <- as.numeric(merge_fix$day_resemption_fct_g)
merge_fix$cold_ischemia_g <- as.numeric(merge_fix$cold_ischemia_g)
merge_fix$luk_ischemia_g <- as.numeric(merge_fix$luk_ischemia_g)
merge_fix$day_hospit_g <- as.numeric(merge_fix$day_hospit_g)
merge_fix$cmv_r <- as.factor(merge_fix$cmv_r)
merge_fix$hcv_r <- as.factor(merge_fix$hcv_r)
merge_fix$ebv_r <- as.factor(merge_fix$ebv_r)
merge_fix$ag_hbs_r <- as.factor(merge_fix$ag_hbs_r)
merge_fix$hiv_r <- as.factor(merge_fix$hiv_r)
merge_fix$transfusion_r <- as.factor(merge_fix$transfusion_r)
merge_fix$code_ttt_ind <- as.factor(merge_fix$code_ttt_ind)
merge_fix$day_ttt_ind <- as.factor(merge_fix$day_ttt_ind)
merge_fix$mach_perf <- as.numeric(merge_fix$mach_perf)
merge_fix$cni_g <- as.factor(merge_fix$cni_g)
merge_fix$csa_g <- as.factor(merge_fix$csa_g)
merge_fix$tacro_g <- as.factor(merge_fix$tacro_g)
merge_fix$mTor_g <- as.factor(merge_fix$mTor_g)
merge_fix$sirolimus_g <- as.factor(merge_fix$sirolimus_g)
merge_fix$everolimus_g <- as.factor(merge_fix$everolimus_g)
merge_fix$apparent_cni_g <- as.factor(merge_fix$apparent_cni_g)
merge_fix$antiprolif_g <- as.factor(merge_fix$antiprolif_g)
merge_fix$mmf_g <- as.factor(merge_fix$mmf_g)
merge_fix$mpa_g <- as.factor(merge_fix$mpa_g)
merge_fix$aza_g <- as.factor(merge_fix$aza_g)
merge_fix$ttt_cortic_g <- as.factor(merge_fix$ttt_cortic_g)
merge_fix$ttt_other_g <- as.factor(merge_fix$ttt_other_g)
merge_fix$prophyl_pnc_g <- as.factor(merge_fix$prophyl_pnc_g)
merge_fix$prophyl_cmv_g <- as.factor(merge_fix$prophyl_cmv_g)
merge_fix$atcdt_diab_g <- as.factor(merge_fix$atcdt_diab_g)
merge_fix$atcdt_dyslip_g <- as.factor(merge_fix$atcdt_dyslip_g)
merge_fix$atcdt_vasc_g <- as.factor(merge_fix$atcdt_vasc_g)
merge_fix$atcdt_card_g <- as.factor(merge_fix$atcdt_card_g)
merge_fix$atcdt_cardvasc_g <- as.factor(merge_fix$atcdt_cardvasc_g)
merge_fix$atcdt_neoplasia_g <- as.factor(merge_fix$atcdt_neoplasia_g)
merge_fix$atcdt_Ksolide_g <- as.factor(merge_fix$atcdt_Ksolide_g)
merge_fix$atcdt_Kspino_g <- as.factor(merge_fix$atcdt_Kspino_g)
merge_fix$atcdt_Kbaso_g <- as.factor(merge_fix$atcdt_Kbaso_g)
merge_fix$atcd_Kmelanome_g <- as.factor(merge_fix$atcd_Kmelanome_g)
merge_fix$atcdt_Khemato_g <- as.factor(merge_fix$atcdt_Khemato_g)
merge_fix$atcdt_nephroBKV_g <- as.factor(merge_fix$atcdt_nephroBKV_g)
merge_fix$atcdt_pregnancy_g <- as.factor(merge_fix$atcdt_pregnancy_g)
merge_fix$incomp_a <- as.factor(merge_fix$incomp_a)
merge_fix$incomp_b <- as.factor(merge_fix$incomp_b)
merge_fix$incomp_abo <- as.factor(merge_fix$incomp_abo)
merge_fix$incomp_dr <- as.factor(merge_fix$incomp_dr)
merge_fix$incomp_ab <- as.factor(merge_fix$incomp_ab)
merge_fix$incomp_bdr <- as.factor(merge_fix$incomp_bdr)
merge_fix$incomp_abdr <- as.factor(merge_fix$incomp_abdr)
merge_fix$ident_a <- as.factor(merge_fix$ident_a)
merge_fix$ident_b <- as.factor(merge_fix$ident_b)
merge_fix$ident_ab <- as.factor(merge_fix$ident_ab)
merge_fix$ident_abdr <- as.factor(merge_fix$ident_abdr)
merge_fix$ident_bdr <- as.factor(merge_fix$ident_bdr)
merge_fix$ident_dr <- as.factor(merge_fix$ident_dr)
merge_fix$ident_dr <- as.factor(merge_fix$ident_dr)
merge_fix$type_d <- as.factor(merge_fix$type_d)
merge_fix$type_cadaver_d <- as.factor(merge_fix$type_cadaver_d)
merge_fix$ecd_scd_d <- as.factor(merge_fix$ecd_scd_d)
merge_fix$code_death_d <- as.factor(merge_fix$code_death_d)
merge_fix$bmi_predon_d <- as.numeric(merge_fix$bmi_predon_d)
merge_fix$weight_predon_d <- as.numeric(merge_fix$weight_predon_d)
merge_fix$height_predon_d <- as.numeric(merge_fix$height_predon_d)
merge_fix$cmv_predon_d <- as.factor(merge_fix$cmv_predon_d)
merge_fix$ebv_predon_d <- as.factor(merge_fix$ebv_predon_d)
merge_fix$hvc_predon_d <- as.factor(merge_fix$hvc_predon_d)
merge_fix$ac_hbs_predon_d <- as.factor(merge_fix$ac_hbs_predon_d)
merge_fix$age_predon_d <- as.numeric(merge_fix$age_predon_d)
merge_fix$hiv_predon_d <- as.numeric(merge_fix$hiv_predon_d)
merge_fix$ac_hbc_predon_d <- as.factor(merge_fix$ac_hbc_predon_)
merge_fix$hta_predon_d <- as.factor(merge_fix$hta_predon_d)
merge_fix$diab_predon_d <- as.factor(merge_fix$diab_predon_d)
merge_fix$dyslip_predon_d <- as.numeric(merge_fix$dyslip_predon_d)
merge_fix$atcdt_arretCardia_predon_d <- as.numeric(merge_fix$atcdt_arretCardia_predon_d)
merge_fix$diuresis_predon_d <- as.factor(merge_fix$diuresis_predon_d)
merge_fix$urea_predon_d <- as.factor(merge_fix$urea_predon_d)
merge_fix$creat_predon_d <- as.factor(merge_fix$creat_predon_d)
```

```{r}
library(corrplot)
library(gplots)
pdf("fixed datas corr.pdf")
plot <- ggpairs(merge_fix[,c(3:8)])
print(plot)
dev.off()
```

