---
title: "Exploration DIVAT immune_compatibility"
author: "alice"
date: "2024-04-16"
output: html_document
---

```{r warning=FALSE}
suppressWarnings(library(Hmisc))
suppressWarnings(library(readxl))
coltype <- c("numeric","numeric","numeric",rep("numeric",11))
immune_compatibility <- read_excel("C:\\Alice\\1-Universitée\\Stages\\M1-centrale\\DATAS\\ALICE_DATAS\\ALL_VARIABLES_KiTGENIE2024.xlsx", sheet = "immune_compatibility",na = "NA",col_types = coltype)
```


```{r}
immune_compatibility_N <- immune_compatibility[complete.cases(immune_compatibility$id_g),]
```

```{r}
dataframe <- data.frame(row.names = c("missing","part","coments") )
lenght <- length(immune_compatibility_N$id_g)
for (col in names(immune_compatibility_N)) {
  if(sum(is.na(immune_compatibility_N[[col]]))!= 0){
    #cat(col ,":" , sum(is.na(immune_compatibility_N[[col]])),"\n")}
    dataframe[col] <- c(sum(is.na(immune_compatibility_N[[col]])),sum(is.na(immune_compatibility_N[[col]]))/lenght,"random")}
}
```

```{r}
write.xlsx(dataframe, file = "C:\\Alice\\1-Universitée\\Stages\\M1-centrale\\DATAS\\Describe\\explore\\explore_NA.xlsx",sheetName = "immune_compatibility", append = TRUE)
```
Missing (NA) :

incomp_abo : 100 -> radom
ident_a : 10 -> random 
ident_b : 11 
ident_dr : 11 
ident_ab : 11 
ident_bdr : 12 
ident_abdr : 12 
incomp_a : 10 
incomp_b : 11 
incomp_dr : 11 
incomp_ab : 11 
incomp_bdr : 12 
incomp_abdr : 12 

```{r}
library(mice)
donnees_imputees <- mice(immune_compatibility_N, method = "cart", m = 5)  
immune_compatibility_N <- complete(donnees_imputees)
```

```{r}
describe(immune_compatibility_N)
```

```{r}
summary(immune_compatibility)
```

```{r warning=FALSE}
library(gplots)
library(corrplot)
correlation_matrix <- cor(immune_compatibility_N[,-1])
corrplot(correlation_matrix,method = "color", type = "upper")
heatmap.2(correlation_matrix,
          Rowv = FALSE, Colv = FALSE,
          dendrogram = "none",
          col = colorRampPalette(c("blue", "white", "red"))(100),
          scale = "none",
          margins = c(10,10))
```
