---
title: "Exploration DIVAT individual"
author: "alice"
date: "2024-04-16"
output: html_document
---

```{r}
suppressWarnings(library(Hmisc))
suppressWarnings(library(readxl))
coltype <- c("numeric","guess","text","guess")
suppressWarnings(individual <- read_excel("C:\\Alice\\1-Universitée\\Stages\\M1-centrale\\DATAS\\ALICE_DATAS\\ALL_VARIABLES_KiTGENIE2024.xlsx", sheet = "individual",na = "NA",col_types = coltype))
```

```{r}
individual_N <- individual[complete.cases(individual$id_ind),]
```


```{r}
describe(individual_N)
```
Replace ABO NA when already known and suppress double row:

```{r}
ind_w_noNA <- individual_N[!is.na(individual_N$abo_ind),c(1,4)]
ind_w_noNA<-unique(ind_w_noNA)

for (i in unique(ind_w_noNA$id_ind)) {
  individual_N$abo_ind[individual_N$id_ind == i & is.na(individual_N$abo_ind)] <- ind_w_noNA$abo_ind[ind_w_noNA$id_ind == i]
}
individual_N <- unique(individual_N)
```

```{r}
dataframe <- data.frame(row.names = c("missing","part","coments") )
lenght <- length(individual_N$id_ind)
#mi3 <- missing2
sum <- 0
for (col in names(individual_N)) {
  if(sum(is.na(individual_N[[col]]))!= 0){
    sum <- sum +sum(is.na(individual_N[[col]]))
    cat(col ,":" , sum(is.na(individual_N[[col]])),"\n")
    #mi3 <- c(mi3,sum(is.na(individual_N[[col]]))/lenght)}
    #dataframe[col] <- c(sum(is.na(individual_N[[col]])),sum(is.na(individual_N[[col]]))/lenght,"random")}
}}
print(sum)
```

```{r}
OUT <- loadWorkbook("C:\\Alice\\1-Universitée\\Stages\\M1-centrale\\DATAS\\NewDATA\\KiTGENIE_CLEAN.xlsx")
```


```{r}
addWorksheet(OUT, "individual")
writeData(OUT, sheet = "individual", x = individual_N,keepNA = TRUE)
```

```{r}
summary(individual)
```

