---
title: "Exploration DIVAT other_grafts"
author: "alice"
date: "2024-04-16"
output: html_document
---

```{r}
suppressWarnings(library(Hmisc))
suppressWarnings(library(readxl))
coltype <- c("text","text","guess","guess","guess","text")
other_grafts <- read_excel("C:\\Alice\\1-Universitée\\Stages\\M1-centrale\\DATAS\\ALICE_DATAS\\ALL_VARIABLES_KiTGENIE2024.xlsx", sheet = "other_grafts",na = "NA",col_types = coltype)
```

```{r}
dataframe <- data.frame(row.names = c("missing","part","coments") )
lenght <- length(other_grafts$id_ind_r)
m2 <- mi3
sum <- 0
for (col in names(other_grafts)) {
  if(sum(is.na(other_grafts[[col]]))!= 0){
    sum <- sum + sum(is.na(other_grafts[[col]]))
    cat(col ,":" , sum(is.na(other_grafts[[col]]))/lenght,"\n")
    m2 <- c(m2,sum(is.na(other_grafts[[col]]))/lenght)}
    #dataframe[col] <- c(sum(is.na(other_grafts[[col]])),sum(is.na(other_grafts[[col]]))/lenght,"random")}
}
print(sum)
```

Missing (NA) :

    - year_og : 1 
    - fail_og : 37 
    - fail_immuno_og : 234 
    
```{r}
write.xlsx(dataframe, file = "C:\\Alice\\1-Universitée\\Stages\\M1-centrale\\DATAS\\Describe\\explore\\explore_NA.xlsx",sheetName = "other_grafts", append = TRUE)
```

```{r}
addWorksheet(OUT, "other_grafts")
writeData(OUT, sheet = "other_grafts", x = other_grafts,keepNA = TRUE)
```




```{r}
describe(other_grafts$num_og)
describe(other_grafts$year_og)
describe(other_grafts$type_og)
describe(other_grafts$fail_og)
describe(other_grafts$fail_immuno_og)
```


```{r}
summary(other_grafts)
```


