---
title: "Exploration DIVAT reccurence_fsgs"
author: "alice"
date: "2024-04-16"
output: html_document
---

```{r}
#coltype <- c("guess","text","guess","guess","guess","text")
reccurence_fsgs <- read_excel("C:\\Alice\\1-Universitée\\Stages\\M1-centrale\\DATAS\\ALICE_DATAS\\ALL_VARIABLES_KiTGENIE2024.xlsx", sheet = "recurrence_fsgs",na = "NA",col_types = "text")
```

```{r}
rec_fsgs_N <- reccurence_fsgs[reccurence_fsgs$center_fsgs == "NANTES",]
```

```{r}
dataframe <- data.frame(row.names = c("missing","part","coments") )
lenght <- length(rec_fsgs_N$id_g)
for (col in names(rec_fsgs_N)) {
  if(sum(is.na(rec_fsgs_N[[col]]))!= 0){
    cat(col ,":" , sum(is.na(rec_fsgs_N[[col]]))/lenght,"\n")}
    #dataframe[col] <- c(sum(is.na(rec_fsgs_N[[col]])),sum(is.na(rec_fsgs_N[[col]]))/lenght,"random")}
}
```
```{r}
addWorksheet(OUT, "recurrence_fsgs")
writeData(OUT, sheet = "recurrence_fsgs", x = rec_fsgs_N)
```


```{r}
write.xlsx(dataframe, file = "C:\\Alice\\1-Universitée\\Stages\\M1-centrale\\DATAS\\Describe\\explore\\explore_NA.xlsx",sheetName = "recurrence_fsgs", append = TRUE)
```

```{r}
describe(reccurence_fsgs)
```
```{r}
summary(reccurence_fsgs)
```


